export { default as ArticleSection } from "./homework33-34/ArticleSection/ArticleSection"
export { default as Header } from "./homework33-34/Header/Header"
export { default as Main } from "./homework33-34/Main/Main"
export { default as NavBar } from "./homework33-34/NavBar/NavBar"
export { default as VoteForSmile } from "./homework33-34/VoteForSmile/VoteForSmile"
export { default as Home } from "./homework33-34/Home/Home"
export { default as HomeWork35 } from "./homework35/HomeWork35/HomeWork35.jsx"
export { default as HomeWork36 } from "./homework36/Homework36/Homework36.jsx"
